server:
  port: 9999
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 130
  application:
    name: stockportfolio
  datasource:
    app: # Datasource for application
      postgres:
        hikari:
          poolName: StockPortfolioPostgresPool
          jdbcUrl: ${JDBC_DATABASE_URL} #jdbc:postgresql://localhost:5432/stockportfolio
          username: ${JDBC_DATABASE_USERNAME} #stockportfolio
          password: ${JDBC_DATABASE_PASSWORD} #stockportfolio
          maximumPoolSize: 2
          idleTimeout: 20000
          maxLifetime: 120000
          minimumIdle: 1
          connectionTimeout: 30000
        jpa:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl_auto: validate
            show_sql: true
    liquibase: # Datasource for liquibase
      postgres:
        hikari:
          poolName: LiquibasePostgresPool
          jdbcUrl:  ${JDBC_DATABASE_URL} #jdbc:postgresql://localhost:5432/stockportfolio
          username: ${JDBC_DATABASE_USERNAME} #stockportfolio
          password: ${JDBC_DATABASE_PASSWORD} #stockportfolio
          maximumPoolSize: 1
  # Settings for liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml


api-key: ${EXCHANGE_API_KEY}
