FROM dockerio.bin.t-mobile.at/centos/postgresql-96-centos7


ADD ./start-sql/install.sh   /usr/share/container-scripts/postgresql/start/install.sh
ADD ./start-sql/create_db.sql /usr/share/container-scripts/postgresql/start/database.sql
